### ISSUE TITLE
Copy of your app on Google Play (Copyleft violation)

### ISSUE THREAD

**Issue by Poussinou** [agateau/cat-avatar-generator-app#7]
Hi @agateau 

I found [this app](https://play.google.com/store/apps/details?id=com.swagselfie.catgenerator) on the Google Play Store. This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under Apache 2 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by agateau** [comment]
Hi, thanks for pointing this out. While this app is of bad taste, the author does not really violate the Apache 2 license: nothing in this license forbids doing what he is doing. The only thing I can contest is that the license links points to the license websites instead of the license itself.

It would have been a different story if the app had been licensed under GPL.

Still, that fork is of very poor taste, so what can be done is to rate it 1 star and explain it is a copy. Just did that.

**Comment by Poussinou** [comment]
Hum, I had not seen that he had put a link to the license.

Anyway, this app is down, I don't know why, maybe the fake developer is following this repo, I don't know

Will close for now, but please if you find any other copy, please copy paste the link here so I can track the fake developer, thanks in advance.

**Comment by Korb** [comment]
> I found [this app](https://play.google.com/store/apps/details?id=com.swagselfie.catgenerator) on the Google Play Store.

> We're sorry, the requested URL was not found on this server.
